### PR TITLE
Merge DME 1.0.0

### PR DESCRIPTION
**Pull request by Miepee**
This "merges" everything from DME 1.0.0. Hooking works on Linux, reading and writing bytes works via usual sudo perms. Haven't tested on any other OS.

Anything that involved QT has been slightly modified: `std::string`s were used in favour of `QStrings`, and the DolphinAccessor that referenced SConfig now directly assigns the default value.
DME GUI also supported changing MEM1 and MEM2 via the settings. Dunno if we need this, currently it uses the hardcoded values.

Current issues:
- conflicts with the get_status PR

---

Relevant changelog from what I gathered (may be missing a few):
- Add null pointer checks in DolphinAccessor
- Feature: Specify MEM1/MEM2 Regions / Fix compatibility with Dolphin MEM Override
- Add setting for configuring the threshold to show scanned values in table
- Naming: Dolphin-memory-engine -> dolphin-memory-engine for consistency
- Remove primary cache
- MacOS Support
- Add the `--dolphin-process-name` command-line option. The [undocumented] DME_DOLPHIN_PROCESS_NAME environment variable can be used alternatively.

### CODE REVIEW

**Review by henriquegemignani — APPROVED** [review]

**Comment by henriquegemignani** [comment]
The custom MEM1 and MEM2 sizes I'm fine with being hardcoded, but could maybe later expose a way to let users try to hook with different values.
All I wish from it is being able to in multiworld, handle people using custom memory sizes automatically. But if they'll need to provide some configuration then it's not useful.

**Comment by Miepee** [comment]
Would be nice, but dolphin has a big fat "Enabling memory override will make many games completely unplayable" warning anyway, so I dont care too much about it personally lol

**Comment by abso1utezer0** [comment]
> Would be nice, but dolphin has a big fat "Enabling memory override will make many games completely unplayable" warning anyway, so I dont care too much about it personally lol

Some debug versions of games require higher amounts of memory for the game to boot

**Comment by Miepee** [comment]
Interesting, thanks for the info

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
